# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Gamer.create!(username: Faker::App.name, xbox_tag: Faker::SiliconValley.company, psn_tag: Faker::Name.title , steam_tag: Faker::HitchhikersGuideToTheGalaxy.character)
Gamer.create!(username: Faker::App.name, xbox_tag: Faker::SiliconValley.company, psn_tag: Faker::Name.title , steam_tag: Faker::HitchhikersGuideToTheGalaxy.character)
Gamer.create!(username: Faker::App.name, xbox_tag: Faker::SiliconValley.company, psn_tag: Faker::Name.title , steam_tag: Faker::HitchhikersGuideToTheGalaxy.character)
Gamer.create!(username: Faker::App.name, xbox_tag: Faker::SiliconValley.company, psn_tag: Faker::Name.title , steam_tag: Faker::HitchhikersGuideToTheGalaxy.character)
Gamer.create!(username: Faker::App.name, xbox_tag: Faker::SiliconValley.company, psn_tag: Faker::Name.title , steam_tag: Faker::HitchhikersGuideToTheGalaxy.character)
Gamer.create!(username: Faker::App.name, xbox_tag: Faker::SiliconValley.company, psn_tag: Faker::Name.title , steam_tag: Faker::HitchhikersGuideToTheGalaxy.character)
Gamer.create!(username: Faker::App.name, xbox_tag: Faker::SiliconValley.company, psn_tag: Faker::Name.title , steam_tag: Faker::HitchhikersGuideToTheGalaxy.character)
Gamer.create!(username: Faker::App.name, xbox_tag: Faker::SiliconValley.company, psn_tag: Faker::Name.title , steam_tag: Faker::HitchhikersGuideToTheGalaxy.character)
Gamer.create!(username: Faker::App.name, xbox_tag: Faker::SiliconValley.company, psn_tag: Faker::Name.title , steam_tag: Faker::HitchhikersGuideToTheGalaxy.character)
Gamer.create!(username: Faker::App.name, xbox_tag: Faker::SiliconValley.company, psn_tag: Faker::Name.title , steam_tag: Faker::HitchhikersGuideToTheGalaxy.character)


Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 1)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 1)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 1)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 1)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 1)

Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 2)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 2)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 2)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 2)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 2)

Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 3)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 3)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 3)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 3)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 3)

Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 4)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 4)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 4)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 4)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 4)

Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 5)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 5)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 5)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 5)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 5)

Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 6)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 6)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 6)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 6)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 6)

Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 7)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 7)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 7)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 7)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 7)

Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 8)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 8)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 8)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 8)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 8)

Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 9)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 9)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 9)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 9)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 9)

Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 10)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 10)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 10)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 10)
Review.create!(skill_score: rand(1...10), teammate_score: rand(1...10), communication_score: rand(1...10), play_again_score: rand(1...10), behavior_score: rand(1...10), friend_score: rand(1...10), game: Faker::Space.meteorite, comments: Faker::RickAndMorty.quote, target_id: 10)